### PR TITLE
Use mixins accessors + some misc fixes

### LINKED ISSUE #12021: EIG bug with Glieonia
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Set up an EIG with sweed and glieonia and they work fine.

### The Reality

It has enough water and power but stops producing glowstone and specifically only glowstone after relog/restart. It works until next restart if I set it up again by pulling the seeds out and putting back in.

### Your Proposal

Glieonia normally acts like both a flower and a crop, planted on dirt/grass and not farmland. This could maybe cause it? Idk why else only glieonia would be affected. (sweed in the same EIG as glieonia makes sugar just fine, redlon and lazullia in another EIG also works perfectly)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #13699: Kubatech's WorldMixin will produce a huge number of CallbackInfoReturnable objects
### Your GTNH Discord Username

_No response_

### Your Pack Version

2.3.2

### Your Server

forge server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I found something wrong with memory like this
%6Y3%OK J)79A8%7UH_4LOC
Then I realized that I had a huge amount of CallbackInfoReturnable objects in memory
image
Then I used mixin debug to find this
image

It's on github [here](https://github.com/GTNewHorizons/KubaTech/blob/b2c2a6dfe91696d4ecada95e5e43806ddb144ece/src/main/java/kubatech/mixin/mixins/minecraft/WorldMixin.java#L19)

`World.getBlock()` is a hot method that gets called frequently in the main tick. I think we should use something else instead of this Mixin injection

### The Reality

:(

### Your Proposal

Use something else instead of this injection. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by kuba6000**
- Use mixins accessors instead of reflections
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13699
- Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12021
- Fix very long floating point numbers on some mobs in mob handler (translation fix)
- Some other internal mod changes

### CODE REVIEW

File: src/main/java/kubatech/loaders/MobRecipeLoader.java [hunk 1]
```diff
@@ -92,12 +93,8 @@ public class MobRecipeLoader {
 
     private static final Logger LOG = LogManager.getLogger(Tags.MODID + "[Mob Recipe Loader]");
 
-    private static final String dropFewItemsName = isDeobfuscatedEnvironment ? "dropFewItems" : "func_70628_a";
-    private static final String dropRareDropName = isDeobfuscatedEnvironment ? "dropRareDrop" : "func_70600_l";
-    private static final String setSlimeSizeName = isDeobfuscatedEnvironment ? "setSlimeSize" : "func_70799_a";
     private static final String addRandomArmorName = isDeobfuscatedEnvironment ? "addRandomArmor" : "func_82164_bB";
     private static final String enchantEquipmentName = isDeobfuscatedEnvironment ? "enchantEquipment" : "func_82162_bC";
```
Comment (miozune) [inline src/main/java/kubatech/loaders/MobRecipeLoader.java:112]: forgot to remove?

File: build.gradle [hunk 2]
```diff
@@ -879,6 +879,7 @@ def getManifestAttributes() {
             "ForceLoadAsMod": !containsMixinsAndOrCoreModOnly.toBoolean()
         ]
     }
+    manifestAttributes += ["Main-class": "kubatech.standalone"]
```
Comment (miozune) [inline build.gradle:882]: Won't this get wiped when updating buildscript?

File: src/main/java/kubatech/commands/CommandCustomDrops.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+    @Override
+    public int getRequiredPermissionLevel() {
+        return 4;
+    }
+
+    @Override
+    public void processCommand(ICommandSender p_71515_1_, String[] p_71515_2_) {
+
+        if (!Minecraft.getMinecraft()
```
Comment (miozune) [inline src/main/java/kubatech/commands/CommandCustomDrops.java]: `Minecraft` is client-only class. (It doesn't fully crash the server though)

File: src/main/java/kubatech/mixin/mixins/InfernalMobs/InfernalMobsCoreAccessor.java [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.gen.Accessor;
+import org.spongepowered.asm.mixin.gen.Invoker;
+
+import atomicstryker.infernalmobs.common.InfernalMobsCore;
+import atomicstryker.infernalmobs.common.mods.api.ModifierLoader;
+
+@Mixin(value = InfernalMobsCore.class, remap = false)
+public interface InfernalMobsCoreAccessor {
```
Comment (miozune) [inline src/main/java/kubatech/mixin/mixins/InfernalMobs/InfernalMobsCoreAccessor.java]: Since we have source of Infernal Mobs, making these classes public on source code makes more sense.

File: src/main/java/kubatech/mixin/mixins/minecraft/StringTranslateMixin.java [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+import org.spongepowered.asm.mixin.injection.Redirect;
+
+import kubatech.Tags;
+
+@SuppressWarnings("unused")
+@Mixin(value = StringTranslate.class)
+public class StringTranslateMixin {
+
+    @Redirect(
+        method = "Lnet/minecraft/util/StringTranslate;parseLangFile(Ljava/io/InputStream;)Ljava/util/HashMap;",
```
Comment (miozune) [inline src/main/java/kubatech/mixin/mixins/minecraft/StringTranslateMixin.java]: `Unnecessary qualified reference to 'parseLangFile' in target class`
```suggestion
        method = "parseLangFile(Ljava/io/InputStream;)Ljava/util/HashMap;",
```

File: src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+import org.spongepowered.asm.mixin.injection.Redirect;
+
+import kubatech.Tags;
+
+@SuppressWarnings("unused")
+@Mixin(value = Locale.class)
+public class LocaleMixin {
+
+    @ModifyArg(
+        method = "Lnet/minecraft/client/resources/Locale;loadLocaleDataFiles(Lnet/minecraft/client/resources/IResourceManager;Ljava/util/List;)V",
```
Comment (miozune) [inline src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java]: `Unnecessary qualified reference to 'loadLocaleDataFiles' in target class`
```suggestion
        method = "loadLocaleDataFiles(Lnet/minecraft/client/resources/IResourceManager;Ljava/util/List;)V",
```

File: src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+            target = "Lnet/minecraft/client/resources/IResourceManager;getAllResources(Lnet/minecraft/util/ResourceLocation;)Ljava/util/List;"),
+        index = 0,
+        require = 1)
+    private ResourceLocation loadLocaleDataFiles(ResourceLocation resourceLocation) {
+        currentlyTranslating = resourceLocation.getResourceDomain();
+        return resourceLocation;
+    }
+
+    @Redirect(
+        method = "Lnet/minecraft/client/resources/Locale;loadLocaleData(Ljava/io/InputStream;)V",
```
Comment (miozune) [inline src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java]: `Unnecessary qualified reference to 'loadLocaleData' in target class`
```suggestion
        method = "loadLocaleData(Ljava/io/InputStream;)V",
```

File: src/main/java/kubatech/api/utils/ItemUtils.java [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+
+    public static ItemStack readItemStackFromNBT(NBTTagCompound compound) {
+        if (compound.hasKey("id", 2)) return ItemStack.loadItemStackFromNBT(compound);
+
+        ItemStack stack = new ItemStack(
+            Item.getItemById(compound.getInteger("id")),
+            compound.getInteger("Count"),
+            compound.getInteger("Damage"));
+
+        if (compound.hasKey("tag", 10)) stack.stackTagCompound = compound.getCompoundTag("tag");
```
Comment (miozune) [inline src/main/java/kubatech/api/utils/ItemUtils.java]: Use `net.minecraftforge.common.util.Constants.NBT`

File: src/main/java/kubatech/api/utils/ItemUtils.java [hunk 9]
```diff
@@ -0,0 +1,35 @@
...
+
+import kubatech.mixin.mixins.minecraft.ItemStackAccessor;
+
+public class ItemUtils {
+
+    public static NBTTagCompound writeItemStackToNBT(ItemStack stack) {
+        NBTTagCompound compound = new NBTTagCompound();
+
+        compound.setInteger("id", Item.getIdFromItem(((ItemStackAccessor) (Object) stack).getItem()));
+        compound.setInteger("Count", stack.stackSize);
```
Comment (miozune) [inline src/main/java/kubatech/api/utils/ItemUtils.java]: I assume the purpose of this method is for saving stack size larger than `byte`. Why not call `ItemStack#writeToNBT` and then overwrite `Count` tag with integer? That way itemstack accessor can be removed, and potentially it works with modifications made by other mods.

File: src/main/java/kubatech/loaders/MobRecipeLoader.java (hunk 1 above)
Comment (kuba6000) [reply src/main/java/kubatech/loaders/MobRecipeLoader.java:112]: Still used to determine if the  mob class is overriding them https://github.com/GTNewHorizons/KubaTech/blob/b91f9ba5a7d1e32ad11c4d7499882dfb7cbd002f/src/main/java/kubatech/loaders/MobRecipeLoader.java#L844-L855

File: src/main/java/kubatech/commands/CommandCustomDrops.java (hunk 3 above)
Comment (kuba6000) [reply src/main/java/kubatech/commands/CommandCustomDrops.java]: Changed to diffrent logic

File: src/main/java/kubatech/mixin/mixins/minecraft/StringTranslateMixin.java (hunk 5 above)
Comment (kuba6000) [reply src/main/java/kubatech/mixin/mixins/minecraft/StringTranslateMixin.java]: Done

File: src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java (hunk 6 above)
Comment (kuba6000) [reply src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java]: Done

File: src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java (hunk 7 above)
Comment (kuba6000) [reply src/main/java/kubatech/mixin/mixins/minecraft/LocaleMixin.java]: Done

File: src/main/java/kubatech/api/utils/ItemUtils.java (hunk 9 above)
Comment (kuba6000) [reply src/main/java/kubatech/api/utils/ItemUtils.java]: Yeah, simplified

File: src/main/java/kubatech/loaders/MobRecipeLoader.java (hunk 1 above)
Comment (miozune) [reply src/main/java/kubatech/loaders/MobRecipeLoader.java:112]: oh I see

**Comment by miozune** [comment]
It would be better to pass formatted decimal string to translator method than mixining into vanilla. It has an advantage of utilizing `DecimalFormat` for more detailed configuration.
Example: https://github.com/GTNewHorizons/GTNEIOrePlugin/blob/749ee1a1860b65ef516d97224aad964b68bfbe09/src/main/java/pers/gwyog/gtneioreplugin/plugin/gregtech5/PluginGT5UndergroundFluid.java#L104

File: src/main/java/kubatech/mixin/mixins/InfernalMobs/InfernalMobsCoreAccessor.java (hunk 4 above)
Comment (kuba6000) [reply src/main/java/kubatech/mixin/mixins/InfernalMobs/InfernalMobsCoreAccessor.java]: https://github.com/GTNewHorizons/Infernal-Mobs/pull/13

Comment (kuba6000) [reply src/main/java/kubatech/mixin/mixins/InfernalMobs/InfernalMobsCoreAccessor.java]: Done

File: build.gradle (hunk 2 above)
Comment (kuba6000) [reply build.gradle:882]: It will, but there is no other way I think

Comment (miozune) [reply build.gradle:882]: Well it's your mod, you can maintain it

**Comment by kuba6000** [comment]
> It would be better to pass formatted decimal string to translator method than mixining into vanilla. It has an advantage of utilizing `DecimalFormat` for more detailed configuration. Example: https://github.com/GTNewHorizons/GTNEIOrePlugin/blob/749ee1a1860b65ef516d97224aad964b68bfbe09/src/main/java/pers/gwyog/gtneioreplugin/plugin/gregtech5/PluginGT5UndergroundFluid.java#L104

Maybe, but my mixin is also working and I can just use StatCollector.translateToLocalFormatted or String.format with number formatting from lang file for a simple text.

File: build.gradle (hunk 2 above)
Comment (kuba6000) [reply build.gradle:882]: > Well it's your mod, you can maintain it

Ye, its just to show a tea when you double click on a mod in files so not that important anyway

**Comment by miozune** [comment]
Hmm, I don't like it, but it won't harm other mods, so it's fine I guess

**Review by miozune — APPROVED** [review]
